### ISSUE TITLE
Electron Builds

### ISSUE THREAD

**Issue by braunsonm** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2#95]
**Describe the feature**
Support electron native builds

**Stakeholder Use-case**
The stakeholder requested this as a nice to have.

**Tasks**
- [x] Build the electron app referencing the localhost dev server
- [x] Adjust it to use the distribution files made on build
- [x] Integrate it into the build pipeline

**⏰ Estimated Time**
2-3 hours.
